#ifndef CINC_LEXER_H
#define CINC_LEXER_H

typedef enum {
    // Single character tokens
    TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN,
    TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
    TOKEN_LEFT_BRACKET, TOKEN_RIGHT_BRACKET,
    TOKEN_COMMA, TOKEN_DOT, TOKEN_SEMICOLON,
    TOKEN_COLON, TOKEN_QUESTION, TOKEN_TILDE,

    // One or two-character toknes
    TOKEN_MINUS, TOKEN_MINUS_MINUS, TOKEN_MINUS_EQUAL, TOKEN_ARROW,
    TOKEN_PLUS, TOKEN_PLUS_PLUS, TOKEN_PLUS_EQUAL,
    TOKEN_STAR, TOKEN_STAR_EQUAL,
    TOKEN_SLASH, TOKEN_SLASH_EQUAL,
    TOKEN_PERCENT, TOKEN_PERCENT_EQUAL,

    TOKEN_AMEPRSAND, TOKEN_AMEPRSAND_AMPERSAND, TOKEN_AMPERSAND_EQUAL,
    TOKEN_PIPE, TOKEN_PIPE_PIPE, TOKEN_PIPE_EQUAL,
    TOKEN_CARET, TOKEN_CARET_EQUAL,
    TOKEN_EQUAL, TOKEN_EQUAL_EQUAL,
    TOKEN_BANG, TOKEN_BANG_EQUAL,

    TOKEN_GREATER, TOKEN_GREATER_EQUAL, TOKEN_GREATER_GREATER,
    TOKEN_GREATER_GREATER_EQUAL,
    TOKEN_LESS, TOKEN_LESS_EQUAL, TOKEN_LESS_LESS,
    TOKEN_LESS_LESS_EQUAL,

    // Literals
    TOKEN_IDENTIFIER, TOKEN_CONSTANT, TOKEN_STRING_LITERAL, TOKEN_CHAR_LITERAL,

    // Keywords (Storage and types)
    TOKEN_AUTO, TOKEN_REGISTER, TOKEN_STATIC, TOKEN_EXTERN, TOKEN_TYPEDEF,
    TOKEN_VOID, TOKEN_CHAR, TOKEN_SHORT, TOKEN_INT, TOKEN_LONG, TOKEN_FLOAT, TOKEN_DOUBLE,
    TOKEN_SIGNED, TOKEN_UNSIGNED, TOKEN_CONST, TOKEN_VOLATILE,

    // Keywords (Control flow)
    TOKEN_IF, TOKEN_ELSE, TOKEN_SWITCH, TOKEN_CASE, TOKEN_DEFAULT,
    TOKEN_WHILE, TOKEN_DO, TOKEN_FOR,
    TOKEN_GOTO, TOKEN_CONTINUE, TOKEN_BREAK, TOKEN_RETURN,
    TOKEN_SIZEOF,

    // Misc
    TOKEN_EOF, TOKEN_ERROR
} token_type_e;

typedef struct {
    token_type_e type;
    const char *start;
    int line;
    int length;
} token_t;

void lexer_init(const char *source);
token_t lexer_scan_token(void);

#endif
