#ifndef CINC_LEXER_H
#define CINC_LEXER_H

typedef enum {
    // Single character tokens
    TOKEN_LET_PAREN, TOKEN_RIGHT_PAREN,
    TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
    TOKEN_LEFT_BRACKET, TOKEN_RIGHT_BRACKET,
    TOKEN_COMMA, TOKEN_DOT, TOKEN_SEMICOLON,
    TOKEN_PLUS, TOKEN_MINUS, TOKEN_STAR, TOKEN_SLASH,
    TOKEN_PERCENT, // others
    TOKEN_BANG, TOKEN_EQUAL,
    TOKEN_LESS, TOKEN_GREATER,

    // Multi-character tokens
    TOKEN_PLUS_EQUAL, TOKEN_MINUS_EQUAL,
    TOKEN_STAR_EQUAL, TOKEN_SHALSH_EQUAL,
    TOKEN_BANG_EQUAL, TOKEN_EQUAL_EQUAL,
    TOKEN_LESS_EQUAL, TOKEN_GREATER_EQUAL,
    TOKEN_AND_AND, TOKEN_OR_OR,
    TOKEN_PLUS_PLUS, TOKEN_MINUS_MINUS,
    TOKEN_ARROW,

    // Literals
    TOKEN_IDENTIFIER, TOKEN_NUMBER, TOKEN_CHAR, TOKEN_STRING,

    // Keywords
    TOKEN_IF, TOKEN_ELSE, TOKEN_FOR, TOKEN_WHILE,
    TOKEN_INT, TOKEN_VOID, TOKEN_CHAR_KEYWORD, TOKEN_STRUCT,
    TOKEN_BREAK, TOKEN_CONTINUE, TOKEN_RETURN,

    // Misc
    TOKEN_EOF, TOKEN_ERROR

} token_type_e;

typedef struct {

} token_t;

#endif
